### ISSUE TITLE
Unusual Error

### ISSUE THREAD

**Issue by AsuranDex** [micans/bash-utils#1]
Hi, 
This tool has been incredibly useful for navigating to files in deep locations which is a god send. However ive encountered a rather odd issue. Im not sure what's causing it but this specific path, and the few others like it, all flare up as if it does not exist, however if I tab to get the content of the bookmarked folder, it will show. So clearly terminal understands the path, but for some reason will not cd directly to it, but I can CD to a folder within it. Ive attached a screenshot and attached a TXT of the terminal output, hope this helps, 

Cheers,
Alex 

[Terminal Saved Output.txt](https://github.com/micans/bash-utils/files/2611882/Terminal.Saved.Output.txt)
<img width="1152" alt="screenshot 2018-11-23 at 23 41 42" src="https://user-images.githubusercontent.com/43570309/48962586-908c5f80-ef79-11e8-9dce-6da425eed4e6.png">

**Comment by goedel-gang** [comment]
The problem seems to be the trailing space in your directory name. Fix is on the way but maybe you should have a serious think about what that directory did to you to deserve that ; )

**Comment by micans** [comment]
Hi, thanks for the kind words and reporting this! The latest commit https://github.com/micans/bash-utils/commit/593306fa44ffcd5f722ee6295045dfc57afea296 should hopefully fix this by throwing in some more quotes. Spicy naming!

**Comment by micans** [comment]
This was fixed, then reopened possibly to allow some feedback? Anyway, it was fixed.
