### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by afonsoguerra** [micans/bash-utils#3]
Hi Izaak,

Great feature set in the bash version of apparish and elegant code. It is much easier to install and covers 99.9% of my needs as a complete addict to the original C version. 

The only thing I am missing is that the bash functions wrapping the C version allow mid-name tab completion. 

E.g. - if I have a label named Something_or_other, I can tab complete with "other[TAB]". The bash version I have installed doesn't allow that. Is that on purpose? can the more generic tab completion be implemented? 

Many thanks!
Afonso

**Comment by goedel-gang** [comment]
Hi Afonso,

Thank you : )

It seems that this is a product of relying more on the Bash completion mechanism with `compgen`. Particularly it seems that `compgen -W ... --` doesn't understand how to complete on infixes (possibly I need to have a closer look at `man bash`). Does this mean you were using the completion from `shell-examples`? I'd not noticed it myself as I'm using `zsh`, where the native completion mechanism does understand infixes.

Anyway, I have a tentative fix at
https://github.com/goedel-gang/bash-utils/commit/79f08ec12c9877d6b9733d7a7e27f9659118cb56

Does this fix what you were talking about? It's not a particularly neat way to do it though, maybe we should just move away from `compgen` entirely..

**Comment by afonsoguerra** [comment]
Perfect! That does the trick quite nicely. Thanks for the ultra-fast reply time :)

**Comment by goedel-gang** [comment]
You're very welcome, I've not got anything better to do : )

Thinking about it, the way it now works is that say you have bookmarks `otters` and `another`, and type `to ot<Tab>` it will complete to `another` first. Personally I'd expect it to go to `otters` first, but I'd be interested to hear your thoughts on it.

**Comment by afonsoguerra** [comment]
I will have a play and let you know!

Somehow here it doesn't seem to complete to anything in particular, just gives me all the options that match upon the second tab press.
 
To elaborate on my use-case for the record: I have numbers at the start of directory names. I have these numbered directories inside a portal. The complete file names within each directory/project often have people's names. I frequently forget the numbers, but with the tab completion like this can easily find them! 
How much this use-case is generalisable, I don't know.

**Comment by micans** [comment]
Thanks Izaak! Hey Afonso, initially I was confused about your usage, but now I remember the numbering convention that you use. Makes sense!
When you write *gives me all the options that match upon the second tab press.* I assume that you don't use cyclic tab completion, correct?

**Comment by goedel-gang** [comment]
°_°     uh oh. Not completing to anything in particular sounds like a bug. Can you elaborate at all?
I have a minimal setup at https://gist.github.com/goedel-gang/fe51f674e36523fe2a0351e366c6da0e that seems to work.

Meanwhile I added the feature I was talking about in
https://github.com/goedel-gang/bash-utils/commit/6bbff2153bcbd7aee2eeaf025a8ceb439848a169#diff-d331283e0b634559df5fbea310f9510b.

ahhh stijn beat me to it

**Comment by afonsoguerra** [comment]
Hi Stijn! 
No, clearly I don't! I never thought about it, but now it is becoming clear what the problems are in that scenario. I seem to have a vague recollection of discussing this with you some years ago... but I don't fully remember the details of the outcome. My apparix functions have been moved unchanged for the past decade or so :)

**Comment by micans** [comment]
I am confused now. Izaak's initial fix did not quite work for me. If I apply this:
```
@@ -487,6 +485,7 @@ if [[ -n "$BASH_VERSION" ]]; then
         local IFS=$'\n'
         COMPREPLY=()
         if [[ "$COMP_CWORD" == 1 ]]; then
+            # read_array <(cut -f2 -d, "$APPARIXRC" "$APPARIXEXPAND" | grep -F "$tag")
             read_array <(cut -f2 -d, "$APPARIXRC" "$APPARIXEXPAND")
             local tags=( "${izaak_array[@]}" )
             read_array <(compgen -W "${tags[*]}" -- "$tag")
```
and use the outcommented line rather than the one following it, then I can do infix-completion on apparix bookmarks. I am also confused as I am not clear on how I beat Izaak ... :-)

**Comment by goedel-gang** [comment]
euhhh I'm not sure what's happening now

I'm another couple of commits ahead. A couple of my intermediate commits quite badly broke some bits of apparix. Probably portal-expand is currently broken in upstream `master`, unless you happen to have `nullglob` set, and I also had another commit that made portal-expand clobber `apparixrc`.

My completion code looks quite different now to make it complete on prefixes first, and not duplicate completions on empty words.

**Comment by micans** [comment]
Allright. How about we just have an outcommented line that allows infix completion. Do you have things in a working state? Then I'd be happy with a PR. No rush though, other things may be more important.

**Comment by afonsoguerra** [comment]
Ah, I miss breaking Stijn's code... the nostalgia...
