### ISSUE TITLE
Problem with xargs in .bourne-apparish using BASH_VERSION 4.4.20(1)-release

### ISSUE THREAD

**Issue by marceloandrioni** [micans/bash-utils#6]
Hello, first thing, thanks for writing apparix, I have been using the C version for years now, it's really useful for people with "deep" directory trees.

I reinstalled my system and tried to start using the "shell only" version, but I am having some problems when using the TAB completion. After I bookmark some directory (e.g. conf), if I try to issue `to con` and press TAB, I get the error:
`to conxargs: command: No such file or directory`
If I type the full path (`to conf`) and press Enter, it works.

The "solution" I found was to replace the lines
```
            read_array <(_apparix_compgen_bm "$tag" | \                         
                xargs -d $'\n' command printf "%q\n")                                                             
            COMPREPLY=( "${goedel_array[@]}" ) 
```
with `:` in .bourne-apparish. But whit this solution I loose the TAB completion.

Would you have any suggestion on how to fix this issue?

Thank you!

System:
BASH_VERSION = 4.4.20(1)-release
Linux Mint 19.3
Linux 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by micans** [comment]
Hi Marcelo,
the issue is that you don't have the program `xargs` in your system. While it is possible to find a workaround for that, could you try installing it? Or perhaps it is installed in your system, but its location is not in your PATH variable. It is actually slightly surprising xargs is not available to you, as it is fairly standard. Could you check this please?
Thanks,
Stijn

**Comment by marceloandrioni** [comment]
Hi @micans, thank you for the promptly reply.
I checked my path and xargs is present:
```
$ which xargs
/usr/bin/xargs
$ xargs --version
xargs (GNU findutils) 4.7.0-git
```
I also tried to replace the line
```
read_array <(_apparix_compgen_bm "$tag" | \                       
    xargs -d $'\n' command printf "%q\n")
```
with
```
read_array <(_apparix_compgen_bm "$tag" | \                         
/usr/bin/xargs -d $'\n' command /usr/bin/printf "%q\n")
```
but the problem remains. I will try to investigate further what is happening.

Thank you.

**Comment by marceloandrioni** [comment]
Hi again @micans. I managed to get a solution. In the line
```
read_array <(_apparix_compgen_bm "$tag" | \                       
    xargs -d $'\n' command printf "%q\n")
```
I just removed the `command` argument:
```
read_array <(_apparix_compgen_bm "$tag" | \                       
    xargs -d $'\n' printf "%q\n")
```
and now everything works.

I will be closing this issue. Thank you very much.

**Comment by micans** [comment]
Thanks, I was in a rush and misread things. So `command` was the issue, as indeed indicated by the error. That's good to know. Command is a bash builtin, but your bash seems recent enough. Main thing is you fixed it.

**Comment by micans** [comment]
The issue manifests itself when completing on the bookmarks themselves. So pressing `to BOOKMARK <space><tab>` works as expected and completes on subdirectories of the target, but `to BOOKMARK<tab>` *should* complete on bookmarks but doesn't, with the error as reported here.

**Comment by micans** [comment]
Well this issue was not handled with any grace by me. The current code has @marceloandrioni's fix and works, that's at least something. Happy bm.
